FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Install poetry
RUN pip install poetry

# Copy only the dependency files to leverage Docker cache
COPY poetry.lock pyproject.toml ./

# Install dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-root --no-dev

# Copy the rest of the application code
COPY . .

# Copy the test runner script
COPY tests/run_tests.sh .
RUN chmod +x run_tests.sh

# Set the entrypoint to our test runner script
CMD ["./run_tests.sh"] 