FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install poetry
RUN pip install poetry

WORKDIR /app

# Copy only the dependency files first
COPY pyproject.toml poetry.lock ./

# Copy the project files
COPY persona ./persona/
COPY server/ ./server/
COPY tests/ ./tests/

# Install dependencies and the package
RUN poetry config virtualenvs.create false \
    && poetry install --with dev

# Command to run tests
CMD ["pytest", "-v", "tests/"] 